### ISSUE TITLE
一些龟公UP，请求追加。

### ISSUE THREAD

**Issue by jueduilingdu08** [aiaimimi0920/fanguigong#1]
252895081
383666009
26108626

ID从上到下分别是：
无我2004
京东戏精周报
赛雷三分钟

还有发现我再提交，兄弟加油。

**Comment by jueduilingdu08** [comment]
另外，建议兄弟增加一个霸屏的那个隐藏和显示的开关。因为我发现有一些我没拉黑的，但我点进去后被整个反龟公霸屏了，连拉黑都点不到。

弄一个隐藏开关，好让我评论区骂一骂，然后再拉黑，毕竟已经提醒我，我知道了。

每次都要把整个插件关了来操作，操作完再打开还是有点费劲。

**Comment by jueduilingdu08** [comment]
还有一个。

1556651916  小黛晨读

**Comment by aiaimimi0920** [comment]
> 另外，建议兄弟增加一个霸屏的那个隐藏和显示的开关。因为我发现有一些我没拉黑的，但我点进去后被整个反龟公霸屏了，连拉黑都点不到。
> 
> 弄一个隐藏开关，好让我评论区骂一骂，然后再拉黑，毕竟已经提醒我，我知道了。
> 
> 每次都要把整个插件关了来操作，操作完再打开还是有点费劲。

好的好的，我改下代码

**Comment by aiaimimi0920** [comment]
@jueduilingdu08  改好了，0.7版本更新，名单更新可能有延迟，设定是一天一更
