### ISSUE TITLE
龟公uid

### ISSUE THREAD

**Issue by lishi-J** [aiaimimi0920/fanguigong#2]
352735241
![B)S@F0)KR8(Z6YH$%)2AS(E](https://github.com/user-attachments/assets/9d8f2f02-8836-4f00-a472-093b39d68b8a)

**Comment by aiaimimi0920** [comment]
收到。
有点难评，看了大多数视频，基本都是jd的电脑经销商的广告，所以在接一个jd的电脑经销商的广告问题好像也不大。
不过还是先加入黑名单吧，要是有争议，可能会放出来。

**Comment by lishi-J** [comment]
嗯嗯
