### ISSUE TITLE
新龟追加请求

### ISSUE THREAD

**Issue by histion** [aiaimimi0920/fanguigong#3]
![QQ_1730013343398](https://github.com/user-attachments/assets/bb3c406f-4811-47f1-82b2-cb86e034def4)
uid：384701769  亦歌电竞

**Comment by aiaimimi0920** [comment]
加，马上加

**Comment by aiaimimi0920** [comment]
已添加，注意更新时间会滞后一天（脚本逻辑是每天更新一次名单）
