### ISSUE TITLE
龟龟

### ISSUE THREAD

**Issue by HectorMa89** [aiaimimi0920/fanguigong#4]
https://www.bilibili.com/video/BV1NV18Y1Esj/?spm_id_from=333.999.0.0&vd_source=9594d453f38deb4cf67792eabb225602
b站 [大头鹰7z故事](https://space.bilibili.com/444143585)

**Comment by aiaimimi0920** [comment]
加，马上加

**Comment by aiaimimi0920** [comment]
已添加，注意更新时间会滞后一天（脚本逻辑是每天更新一次名单）
