### ISSUE TITLE
氣焰極度囂張

### ISSUE THREAD

**Issue by rioce** [aiaimimi0920/fanguigong#5]
![Screenshot 2024-11-02 162224](https://github.com/user-attachments/assets/fd73f675-d2f0-4782-8177-84abba2abc31)
resource: https://space.bilibili.com/2048571423/

**Comment by aiaimimi0920** [comment]
get it ，加上加上

**Comment by aiaimimi0920** [comment]
已更新，应该明天会自动更新名单，还多更新了几个还在发jd广告的up
